### ISSUE TITLE
Vehicle ID & exlcude counting

### ISSUE THREAD

**Issue by akshu281** [nicholaskajoh/ivy#42]
Dear Author,

When executing this vehicle counter, vehicle ID is in hex format. How do I use normal IDs like 1,2,3.. etc instead of this format to track the same. Could  you please suggest a workaround ?

Also, I am trying to use this approach to just track the vehicle in a ROI and do not want to count at the moment. I have excluded the counting part (attempt_count module) and just based on the mctf threshold I am deleting (del self.blobs[blob_id]) or just retaining the blob as such (self.blobs[blob_id] = blob) inside the loop blob_list. Is there any thing else I just should be paying attention to so the IDs are retained and tracked ?

Thank you !

**Comment by nicholaskajoh** [comment]
Hey @akshu281,

The initial implementation used normal ids like you want it, however this was changed because generating uuids on the fly is much simpler than keeping track of the last numeric id assigned (I believe simple is better than complex 🙂). That said, I struggle to see how having numeric ids will help in your use case. Using vehicle ids to count will give you very inaccurate results. I had such an implementation but removed it because the results were generally poor (this is largely due to tracking failures).

I think logging/counting (or doing whatever else you want) before a blob is deleted is enough.

https://github.com/nicholaskajoh/ivy/blob/5bd9c4de49b4cddf8f2603e01778f58ec90c5c52/VehicleCounter.py#L62-L64

You don't have to exclude the counting part. If you don't add any counting lines (empty list basically), no counting would be done.

Also I don't think it's a good idea to not delete blobs. Depending on how long your video is and how many vehicles are there, you might choke your machine's memory/slow down processing.

**Comment by akshu281** [comment]
Thank You for the inputs. Understood the use of uuids here in this case. I have incorporated the changes as directed.
