### ISSUE TITLE
yolo.py image_blob = cv2.dnn.blobFromImage

### ISSUE THREAD

**Issue by jpsolorzanoa** [nicholaskajoh/ivy#71]
Hello, I've setup this repo on wsl2 ubuntu22.04 with opencv 4.5.5 cuda enabled 11.7. Hoever unless I setup this 608 x 608 images size or larger, won't get any detection or will get like ghost detection or frozen boxes. Same video on windows works fine. What could it be?.

`image_blob = cv2.dnn.blobFromImage(image, scale, (608, 608), (0, 0, 0), True, crop=False)`
<img width="815" alt="Screenshot 2022-05-21 221522" src="https://user-images.githubusercontent.com/36748981/169676717-7eb99094-af4d-46cf-b782-ca77da30c369.png">

**Comment by nicholaskajoh** [comment]
Hmmm... Interesting! I have no idea. I've not run Ivy on WSL before. But I don't think the detection and tracking issues are being caused by it (primarily at least). Ivy could use some (actually, lots of) improvement but with what exists, you will get better results by:
- Using a camera/video with a high frame rate and resolution. Of course this means slower processing so it's a trade-off.
- Tweaking the MCDF, MCTF and DI to suit your video. See https://github.com/nicholaskajoh/ivy/blob/master/settings.py#L50-L72.
